# Generated by Django 4.2.3 on 2023-08-21 19:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('manager', 'manager'), ('developer', 'developer'), ('qa', 'qa')], default='manager', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('submission_date', models.DateField()),
                ('developer', models.ManyToManyField(blank=True, null=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('managers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to='BugMangement.customuser')),
                ('qa', models.ManyToManyField(blank=True, null=True, to='BugMangement.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=50, unique=True)),
                ('bug_description', models.TextField(blank=True)),
                ('deadline', models.DateField()),
                ('screenshot', models.ImageField(blank=True, upload_to='bug_screenshots/')),
                ('bug_type', models.CharField(choices=[('feature', 'feature'), ('bug', 'bug')], default='bug', max_length=20)),
                ('status', models.CharField(choices=[('new', 'new'), ('started', 'started'), ('completed', 'completed'), ('resolved', 'resolved')], default='new', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bugs', to='BugMangement.customuser')),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bugs', to='BugMangement.customuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='BugMangement.project')),
            ],
        ),
    ]
