# Generated by Django 4.2.3 on 2023-08-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugMangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='submission_date',
            field=models.DateField(null=True),
        ),
    ]
