# Generated by Django 4.2.3 on 2023-08-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugMangement', '0002_alter_project_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='submission_date',
        ),
    ]
