# Generated by Django 4.2.3 on 2023-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugMangement', '0003_remove_customuser_gender_remove_project_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='BugMangement.customuser'),
        ),
    ]
